### ISSUE TITLE
CoC long version does not incorporate short version content

### ISSUE THREAD

**Issue by jazzace** [macadminsdotorg/codeofconduct#13]
Most of the Policies in the Long Version of the CoC are related to bullet point 3 from the short version. This gives the impression that only _that_ point is important and enforceable. While I view enforcement as a last resort mechanism—the Community should self-manage as much as possible—I do think the CoC should be more explicit in saying that all principles in the CoC are important and enforceable, not just harassment. I'll consider creating a pull request for my own issue unless someone beats me to it.

**Comment by mrowell** [comment]
I've worked this into https://github.com/macadminsdotorg/codeofconduct/pull/20
