### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by rderewianko** [macadminsdotorg/codeofconduct#8]
That @macmule guy posted a new version in #announcments. I read through it to ensure I wasn't harassing him too much..

The link for
"Please see this document **Dispute Resolution** for full details on resolution steps." Shows a lovely 404 page, and as much as I enjoy Github's 404 page, and find it a bit amusing that dispute resolution doesn't exist I feel there should be.

- RD

**Comment by acodega** [comment]
The CoC has been updated. Thanks for bringing this to our attention.
